### ISSUE TITLE
Final list of features and bugs

### ISSUE THREAD

**Issue by maayami** [Anikait143/Simplab#46]
1. About us in the Settings tab. mk done
2. Alerts mk
3. Notification mk
5. Back button in ExperimentDetail mk done
6. Fix Warnings in Teams.js and mk done
7. Files API integration mk done
8. Download file chat/file mk done
10. experiment detail API mk done
11. G-auth remove mk done
12. Scroll auto mk done
14. edit Asignment ani done
15.  All experiments done
16. create team , join team navigate ani done

**Comment by Anikait143** [comment]
edit Assignment problem solved

**Comment by maayami** [comment]
Working on Alerts and notification.
